package com.quizkit.api.model;

/**
 * Date: June 4, 2021
 * Teacher: Mr. Ho
 * Description: This model stores students information related to a QuizCode. QuizCode acts as a unique code per quiz.
 * 
 * @author Ibrahim Rahman <341169092@gapps.yrdsb.ca>
 */
public class StudentQuiz {
    
    /**
     * Stores the unique student quiz code. Unique per student per quiz. Generated by the teacher service.
     */
    public String studentQuizCode;

    /**
     * Stores the student's name.
     */
    public String studentName;

    /**
     * Stores the student's email.
     */
    public String studentEmail;

    /**
     * Stores the quiz ID that the student will be answering. 
     */
    public String quizId;

    /**
     * This is an empty contructor for this model. This is required to deserialized the model from the firebase client.
     */
    public StudentQuiz() {}

    /**
     * Contructor for the Student Quiz. Initializes the model with the given parameters.
     * @param studentQuizCode Stores the unique student quiz code. Unique per student per quiz. Generated by the teacher service. 
     * @param studentName Stores the student's name.
     * @param studentEmail Stores the student's email.
     * @param quizId Stores the quiz ID that the student will be answering. 
     */
    public StudentQuiz (String studentQuizCode, String studentName, String studentEmail, String quizId) {
        
        // Adds the student's quiz code to the StudentQuiz object. 
        this.studentQuizCode = studentQuizCode;

        // Adds the student's name to the StudentQuiz object. 
        this.studentName = studentName;

        // Adds the student's email to the StudentQuiz object. 
        this.studentEmail = studentEmail;

        // Adds the student's quiz ID to the StudentQuiz object. 
        this.quizId = quizId;
    }
}